[versions]
adarshrTestLogger = "4.0.0"
kotest = "5.9.1"
kotlin = "2.0.20"
kover = "0.8.3"
liquibase = "4.29.2"
mapstruct = "1.6.2"
postgresql = "42.7.4"
spotless = "7.0.0.BETA2"
springBoot = "3.3.4"
testcontainers = "1.20.1"

[plugins]
adarshr-testLogger = { id = "com.adarshr.test-logger", version.ref = "adarshrTestLogger" }
benManes-versions = "com.github.ben-manes.versions:0.51.0"
diffplug-spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
gradle-pluginPublish = "com.gradle.plugin-publish:1.3.0"
gradleup-shadow = "com.gradleup.shadow:8.3.2"
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
littlerobots-versionCatalogUpdate = "nl.littlerobots.version-catalog-update:0.8.4"
sonarqube = "org.sonarqube:5.1.0.4882"
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }

[libraries]
adarshr-testLogger-plugin = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "adarshrTestLogger" }
diffplug-spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
gavlyukovskiy-datasourceProxy = "com.github.gavlyukovskiy:datasource-proxy-spring-boot-starter:1.9.2"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.18.0"
kotest-extensions-spring = "io.kotest.extensions:kotest-extensions-spring:1.3.0"
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runnerJunit5 = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotlin-allopen-plugin = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-noarg-plugin = { module = "org.jetbrains.kotlin:kotlin-noarg", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-kover-plugin = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
ninjaSquad-springmockk = "com.ninja-squad:springmockk:4.0.2"
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springBoot" }
spring-boot-dockerCompose = { module = "org.springframework.boot:spring-boot-docker-compose", version.ref = "springBoot" }
spring-boot-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }
spring-boot-starterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springBoot" }
spring-boot-starterDataJpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot" }
spring-boot-starterTest = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-starterWeb = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starterWebflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "springBoot" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "springBoot" }
springdoc-openApiStarterWebMvcUi = "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0"
testcontainers-junitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
